from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from miniorm import Base
from miniorm.orm_types import Text, Number

app = FastAPI()

# Enable CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class Message(BaseModel):
    text: str


# Define Person model
class Person(Base):
    class Meta:
        table_name = "people"
    
    id = Number(pk=True)
    name = Text()
    email = Text()


class UserCreate(BaseModel):
    name: str
    email: str


@app.post("/api/test")
def test_post(message: Message):
    return {"received": message.text}


@app.post("/api/users")
def create_user(user: UserCreate):
    # Create a new Person instance
    new_user = Person(name=user.name, email=user.email)
    # In a real scenario, you'd persist this using a session
    return {
        "id": 1,  # Placeholder - would be generated by DB
        "name": new_user.name,
        "email": new_user.email,
        "message": "User created successfully"
    }


@app.get("/api/users")
def get_users():
    # Placeholder - would query from DB using session
    return {
        "users": [
            {"id": 1, "name": "Example User", "email": "user@example.com"}
        ]
    }

